version: '3'

services:
  app:
    build: .
    image: app
    ports:
      - '3000:3000'
    volumes:
      - ../../:/app
    environment:
      PORT: '3000'
    depends_on: 
      - mysql

  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: db
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: